CREATE TABLE tips (
  id SERIAL PRIMARY KEY,
  creator_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  tipper_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  amount_cents  INTEGER NOT NULL,
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
